services:
  postgres:
    image: postgres:15-alpine
    container_name: aicademy_db
    environment:
      POSTGRES_USER: aicademy
      POSTGRES_PASSWORD: root
      POSTGRES_DB: aicademy_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aicademy_api
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  pgadmin:
    image: dpage/pgadmin4
    container_name: aicademy_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
