services:
  postgres:
    image: postgres:15-alpine
    container_name: aicademy_db
    environment:
      POSTGRES_USER: aicademy
      POSTGRES_PASSWORD: root
      POSTGRES_DB: aicademy_db
      PGADMIN_DEFAULT_EMAIL: aicademy@admin.com
      PGADMIN_DEFAULT_PASSWORD: aicademy123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aicademy -d aicademy_db"]
      interval: 5s
      retries: 5
      timeout: 5s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aicademy_api
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy 
    ports:
      - "8000:8000"

  pgadmin:
    image: dpage/pgadmin4
    container_name: aicademy_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: aicademy@admin.com
      PGADMIN_DEFAULT_PASSWORD: aicademy123
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
